### ISSUE TITLE
pep8 좀 맞춰주세요;;

### ISSUE THREAD

**Issue by hjh010501** [ch4n3-yoon/dimigo-Couple-Searching#2]
**pep8 은 디미고인 백엔드에서 사용하는 파이썬 스타일 가이드 입니다.....;;**

빨리 좀 맞쳐주세요 현기증 납니다 😡🤬😱🤯
<img width="537" alt="2018-08-30 10 35 48" src="https://user-images.githubusercontent.com/17137872/45339328-0022bd80-b5cd-11e8-9a5e-aa4aff7352f1.png">

**Comment by ch4n3-yoon** [comment]
감사합니다. PEP8 적용하였습니다.
